export const MixpanelEvent = {
  AccountDelete: 'account_delete',
  ActionCardClick: 'action_card_click',
  AnalysisCopy: 'analysis_copy',
  AnalysisEditCancel: 'analysis_edit_cancel',
  AnalysisEditComplete: 'analysis_edit_complete',
  AnalysisEditStart: 'analysis_edit_start',
  AnalysisTabChange: 'analysis_tab_change',
  AudioPause: 'audio_pause',
  AudioPlay: 'audio_play',
  AudioSpeedChange: 'audio_speed_change',
  CardRegisterAttempt: 'card_register_attempt',
  CardRegisterFailed: 'card_register_failed',
  CardRegisterSuccess: 'card_register_success',
  ClientAnalysisCreate: 'client_analysis_create',
  ClientCreateSuccess: 'client_create_success',
  ClientCreateFailed: 'client_create_failed',
  ClientDelete: 'client_delete',
  ClientDetailView: 'client_detail_view',
  ClientSessionClose: 'client_session_close',
  ClientSessionRestart: 'client_session_restart',
  ClientUpdateSuccess: 'client_update_success',
  ClientUpdateFailed: 'client_update_failed',
  ComingSoonModalOpened: 'coming_soon_modal_opened',
  CreditRenewalAttempt: 'credit_renewal_attempt',
  CreditRenewalSuccess: 'credit_renewal_success',
  GenogramCreationCompleteClick: 'genogram_creation_complete_click',
  GenogramEditApplyClick: 'genogram_edit_apply_click',
  GenogramEmptyStateClick: 'genogram_empty_state_click',
  GenogramFamilyMemberAdd: 'genogram_family_member_add',
  GenogramFamilyMemberDelete: 'genogram_family_member_delete',
  GenogramGenerationConfirmClick: 'genogram_generation_confirm_click',
  GenogramRelationAdd: 'genogram_relation_add',
  GenogramRelationDelete: 'genogram_relation_delete',
  GenogramReportButtonClick: 'genogram_report_button_click',
  GenogramReportDownloadClick: 'genogram_report_download_click',
  GenogramReportExportClick: 'genogram_report_export_click',
  GenogramReportGenerateCreditInsufficient:
    'genogram_report_generate_credit_insufficient',
  GenogramReportGenerateSuccess: 'genogram_report_generate_success',
  GenogramReportSeminarButtonClick: 'genogram_report_seminar_button_click',
  GenogramReportSeminarModalView: 'genogram_report_seminar_modal_view',
  GenogramReportVerifyComplete: 'genogram_report_verify_complete',
  HandWrittenSessionCreateSuccess: 'hand_written_session_create_success',
  LoginAttempt: 'login_attempt',
  LoginFailed: 'login_failed',
  LoginSuccess: 'login_success',
  Logout: 'logout',
  MultiSessionCreateSuccess: 'multi_session_create_success',
  NoticeDetailView: 'notice_detail_view',
  NoticeListView: 'notice_list_view',
  OnboardingFunnelStarted: 'onboarding_funnel_started',
  PlanDowngradeAttempt: 'plan_downgrade_attempt',
  PlanDowngradeScheduled: 'plan_downgrade_scheduled',
  PlanUpgradeAttempt: 'plan_upgrade_attempt',
  PlanUpgradeFailed: 'plan_upgrade_failed',
  PlanUpgradeSuccess: 'plan_upgrade_success',
  ProgressNoteCopy: 'progress_note_copy',
  ProgressNoteCopyAll: 'progress_note_copy_all',
  ProgressNoteEditCancel: 'progress_note_edit_cancel',
  ProgressNoteEditComplete: 'progress_note_edit_complete',
  ProgressNoteEditStart: 'progress_note_edit_start',
  SessionCreateSuccess: 'session_create_success',
  SessionFilterClient: 'session_filter_client',
  SessionFilterReset: 'session_filter_reset',
  SessionSortChange: 'session_sort_change',
  SignupFailed: 'signup_failed',
  SignupSuccess: 'signup_success',
  SpeakerEditApply: 'speaker_edit_apply',
  SubscriptionCancel: 'subscription_cancel',
  SubscriptionCancelAttempt: 'subscription_cancel_attempt',
  SupervisionRetry: 'supervision_retry',
  TemplatePinToggle: 'template_pin_toggle',
  TemplateSetDefault: 'template_set_default',
  TranscriptEditCancel: 'transcript_edit_cancel',
  TranscriptEditComplete: 'transcript_edit_complete',
  TranscriptEditStart: 'transcript_edit_start',
  UserInfoEditSuccess: 'user_info_edit_success',
} as const;

export type MixpanelEvent = (typeof MixpanelEvent)[keyof typeof MixpanelEvent];

export const MixpanelError = {
  AccountDeleteError: 'account_delete_error',
  AudioPresignedUrlError: 'audio_presigned_url_error',
  CancelSubscriptionRevertError: 'cancel_subscription_revert_error',
  CardRegistrationError: 'card_registration_error',
  ClientAnalysisCreateError: 'client_analysis_create_error',
  CreditRenewalPreviewError: 'credit_renewal_preview_error',
  GenogramReportGenerateFail: 'genogram_report_generate_fail',
  HandWrittenSessionCreateError: 'hand_written_session_create_error',
  LoginFailed: 'login_failed',
  LogoutError: 'logout_error',
  MarkdownEditSaveError: 'markdown_edit_save_error',
  MultiSessionCreateError: 'multi_session_create_error',
  PlanDowngradeError: 'plan_downgrade_error',
  PlanUpgradeError: 'plan_upgrade_error',
  PlanUpgradeFailed: 'plan_upgrade_failed',
  ProgressNoteCreateError: 'progress_note_create_error',
  ProgressNoteRegenerateError: 'progress_note_regenerate_error',
  SessionCreateError: 'session_create_error',
  SignupFailed: 'signup_failed',
  SpeakerChangeError: 'speaker_change_error',
  SubscriptionCancelError: 'subscription_cancel_error',
  TranscriptSaveError: 'transcript_save_error',
  UserInfoEditFailed: 'user_info_edit_failed',
} as const;

export type MixpanelError = (typeof MixpanelError)[keyof typeof MixpanelError];
