export const MixpanelEvent = {
  // ─── Auth ───────────────────────────────────────────
  AuthFormSwitch: 'auth_form_switch',
  LoginAttempt: 'login_attempt',
  LoginFailed: 'login_failed',
  LoginSuccess: 'login_success',
  LoginOAuthCallback: 'login_oauth_callback',
  Logout: 'logout',
  LogoutConfirmView: 'logout_confirm_view',
  SignupAttempt: 'signup_attempt',
  SignupFailed: 'signup_failed',
  SignupSuccess: 'signup_success',
  PhoneVerificationRequest: 'phone_verification_request',
  PhoneVerificationVerify: 'phone_verification_verify',
  AccountDelete: 'account_delete',
  AccountDeleteConfirmView: 'account_delete_confirm_view',
  PasswordResetRequestAttempt: 'password_reset_request_attempt',
  PasswordResetRequestSuccess: 'password_reset_request_success',
  PasswordResetRequestFailed: 'password_reset_request_failed',
  PasswordUpdateAttempt: 'password_update_attempt',
  PasswordUpdateSuccess: 'password_update_success',
  PasswordUpdateFailed: 'password_update_failed',

  // ─── Home ───────────────────────────────────────────
  ActionCardClick: 'action_card_click',
  SessionCardClick: 'session_card_click',
  WelcomeBannerView: 'welcome_banner_view',
  WelcomeBannerDismiss: 'welcome_banner_dismiss',

  // ─── Session Creation ──────────────────────────────
  MultiSessionCreateModalOpen: 'multi_session_create_modal_open',
  MultiSessionCreateModalClose: 'multi_session_create_modal_close',
  MultiSessionCreateAttempt: 'multi_session_create_attempt',
  MultiSessionCreateSuccess: 'multi_session_create_success',
  MultiSessionStepChange: 'multi_session_step_change',
  MultiSessionFileAdd: 'multi_session_file_add',
  MultiSessionFileRemove: 'multi_session_file_remove',
  HandWrittenSessionCreateModalOpen: 'hand_written_session_create_modal_open',
  HandWrittenSessionCreateModalClose: 'hand_written_session_create_modal_close',
  HandWrittenSessionCreateAttempt: 'hand_written_session_create_attempt',
  HandWrittenSessionCreateSuccess: 'hand_written_session_create_success',

  // ─── Session List ──────────────────────────────────
  SessionFilterClient: 'session_filter_client',
  SessionFilterReset: 'session_filter_reset',
  SessionSortChange: 'session_sort_change',

  // ─── Session Detail ────────────────────────────────
  SessionTabChange: 'session_tab_change',
  SessionTabChangeConfirmView: 'session_tab_change_confirm_view',
  SessionTabChangeConfirm: 'session_tab_change_confirm',
  SessionTabChangeCancel: 'session_tab_change_cancel',

  // ─── Audio Player ──────────────────────────────────
  AudioPlay: 'audio_play',
  AudioPause: 'audio_pause',
  AudioSpeedChange: 'audio_speed_change',
  AudioSeek: 'audio_seek',
  AudioForward: 'audio_forward',
  AudioBackward: 'audio_backward',
  AudioComplete: 'audio_complete',

  // ─── Transcript ────────────────────────────────────
  TranscriptEditStart: 'transcript_edit_start',
  TranscriptEditComplete: 'transcript_edit_complete',
  TranscriptEditCancel: 'transcript_edit_cancel',
  TranscriptSegmentDeleteConfirmView: 'transcript_segment_delete_confirm_view',
  TranscriptSegmentDeleteConfirm: 'transcript_segment_delete_confirm',
  SpeakerEditApply: 'speaker_edit_apply',

  // ─── Progress Note ─────────────────────────────────
  ProgressNoteEditStart: 'progress_note_edit_start',
  ProgressNoteEditComplete: 'progress_note_edit_complete',
  ProgressNoteEditCancel: 'progress_note_edit_cancel',
  ProgressNoteCopy: 'progress_note_copy',
  ProgressNoteCopyAll: 'progress_note_copy_all',
  ProgressNoteRegenerateModalOpen: 'progress_note_regenerate_modal_open',
  ProgressNoteRegenerateAttempt: 'progress_note_regenerate_attempt',
  ProgressNoteRegenerateSuccess: 'progress_note_regenerate_success',

  // ─── Analysis ──────────────────────────────────────
  AnalysisCopy: 'analysis_copy',
  AnalysisEditStart: 'analysis_edit_start',
  AnalysisEditComplete: 'analysis_edit_complete',
  AnalysisEditCancel: 'analysis_edit_cancel',
  AnalysisTabChange: 'analysis_tab_change',
  SupervisionRetry: 'supervision_retry',

  // ─── Client ────────────────────────────────────────
  ClientCreateModalOpen: 'client_create_modal_open',
  ClientCreateModalClose: 'client_create_modal_close',
  ClientCreateAttempt: 'client_create_attempt',
  ClientCreateSuccess: 'client_create_success',
  ClientCreateFailed: 'client_create_failed',
  ClientUpdateAttempt: 'client_update_attempt',
  ClientUpdateSuccess: 'client_update_success',
  ClientUpdateFailed: 'client_update_failed',
  ClientDetailView: 'client_detail_view',
  ClientDelete: 'client_delete',
  ClientDeleteConfirmView: 'client_delete_confirm_view',
  ClientSessionClose: 'client_session_close',
  ClientSessionCloseConfirmView: 'client_session_close_confirm_view',
  ClientSessionRestart: 'client_session_restart',
  ClientSessionRestartConfirmView: 'client_session_restart_confirm_view',
  ClientAnalysisModalOpen: 'client_analysis_modal_open',
  ClientAnalysisModalClose: 'client_analysis_modal_close',
  ClientAnalysisCreate: 'client_analysis_create',
  ClientAnalysisSessionSelect: 'client_analysis_session_select',
  ClientAnalysisTemplateSelect: 'client_analysis_template_select',

  // ─── Genogram ──────────────────────────────────────
  GenogramStepChange: 'genogram_step_change',
  GenogramCreationCompleteClick: 'genogram_creation_complete_click',
  GenogramEditApplyClick: 'genogram_edit_apply_click',
  GenogramEmptyStateClick: 'genogram_empty_state_click',
  GenogramFamilyMemberAdd: 'genogram_family_member_add',
  GenogramFamilyMemberEdit: 'genogram_family_member_edit',
  GenogramFamilyMemberDelete: 'genogram_family_member_delete',
  GenogramGenerationConfirmClick: 'genogram_generation_confirm_click',
  GenogramGenerationConfirmModalOpen: 'genogram_generation_confirm_modal_open',
  GenogramRelationAdd: 'genogram_relation_add',
  GenogramRelationDelete: 'genogram_relation_delete',
  GenogramUndo: 'genogram_undo',
  GenogramRedo: 'genogram_redo',
  GenogramResetConfirmView: 'genogram_reset_confirm_view',
  GenogramResetConfirm: 'genogram_reset_confirm',
  GenogramGuideModalOpen: 'genogram_guide_modal_open',
  GenogramGuideStepChange: 'genogram_guide_step_change',
  GenogramGuideComplete: 'genogram_guide_complete',
  GenogramExportModalOpen: 'genogram_export_modal_open',
  GenogramExportBackgroundChange: 'genogram_export_background_change',
  GenogramExportWatermarkToggle: 'genogram_export_watermark_toggle',
  GenogramExportDownload: 'genogram_export_download',

  // ─── Genogram Report ──────────────────────────────
  GenogramReportModalOpen: 'genogram_report_modal_open',
  GenogramReportButtonClick: 'genogram_report_button_click',
  GenogramReportDownloadClick: 'genogram_report_download_click',
  GenogramReportExportClick: 'genogram_report_export_click',
  GenogramReportGenerateCreditInsufficient:
    'genogram_report_generate_credit_insufficient',
  GenogramReportGenerateSuccess: 'genogram_report_generate_success',
  GenogramReportPreviewOpen: 'genogram_report_preview_open',
  GenogramReportSeminarButtonClick: 'genogram_report_seminar_button_click',
  GenogramReportSeminarModalView: 'genogram_report_seminar_modal_view',
  GenogramReportVerifyComplete: 'genogram_report_verify_complete',

  // ─── Template ──────────────────────────────────────
  TemplatePinToggle: 'template_pin_toggle',
  TemplateSetDefault: 'template_set_default',
  TemplateRequestClick: 'template_request_click',

  // ─── Settings ──────────────────────────────────────
  SettingsSectionChange: 'settings_section_change',
  NoticeListView: 'notice_list_view',
  NoticeDetailView: 'notice_detail_view',
  UserInfoEditModalOpen: 'user_info_edit_modal_open',
  UserInfoEditAttempt: 'user_info_edit_attempt',
  UserInfoEditSuccess: 'user_info_edit_success',
  BadgeDetailModalOpen: 'badge_detail_modal_open',

  // ─── Subscription & Payment ────────────────────────
  PlanChangeModalOpen: 'plan_change_modal_open',
  PlanUpgradeConfirmModalOpen: 'plan_upgrade_confirm_modal_open',
  PlanUpgradeAttempt: 'plan_upgrade_attempt',
  PlanUpgradeSuccess: 'plan_upgrade_success',
  PlanUpgradeFailed: 'plan_upgrade_failed',
  PlanDowngradeConfirmModalOpen: 'plan_downgrade_confirm_modal_open',
  PlanDowngradeAttempt: 'plan_downgrade_attempt',
  PlanDowngradeScheduled: 'plan_downgrade_scheduled',
  CardRegistrationModalOpen: 'card_registration_modal_open',
  CardRegisterAttempt: 'card_register_attempt',
  CardRegisterSuccess: 'card_register_success',
  CardRegisterFailed: 'card_register_failed',
  CreditUsageModalOpen: 'credit_usage_modal_open',
  CreditRenewalModalOpen: 'credit_renewal_modal_open',
  CreditRenewalAttempt: 'credit_renewal_attempt',
  CreditRenewalSuccess: 'credit_renewal_success',
  SubscriptionCancel: 'subscription_cancel',
  SubscriptionCancelAttempt: 'subscription_cancel_attempt',
  PaymentResultModalView: 'payment_result_modal_view',

  // ─── Onboarding & Quest ────────────────────────────
  OnboardingFunnelStarted: 'onboarding_funnel_started',
  QuestMissionModalOpen: 'quest_mission_modal_open',
  QuestMissionStartClick: 'quest_mission_start_click',
  QuestMissionCompleteView: 'quest_mission_complete_view',
  TutorialGuideModalOpen: 'tutorial_guide_modal_open',
  TutorialGuideStepChange: 'tutorial_guide_step_change',
  TutorialGuideComplete: 'tutorial_guide_complete',

  // ─── Common ────────────────────────────────────────
  ComingSoonModalOpened: 'coming_soon_modal_opened',
  LockedFeatureModalOpen: 'locked_feature_modal_open',
} as const;

export type MixpanelEvent = (typeof MixpanelEvent)[keyof typeof MixpanelEvent];

export const MixpanelError = {
  AccountDeleteError: 'account_delete_error',
  AudioPresignedUrlError: 'audio_presigned_url_error',
  CancelSubscriptionRevertError: 'cancel_subscription_revert_error',
  CardRegistrationError: 'card_registration_error',
  ClientAnalysisCreateError: 'client_analysis_create_error',
  CreditRenewalPreviewError: 'credit_renewal_preview_error',
  GenogramReportGenerateFail: 'genogram_report_generate_fail',
  HandWrittenSessionCreateError: 'hand_written_session_create_error',
  LoginFailed: 'login_failed',
  LogoutError: 'logout_error',
  MarkdownEditSaveError: 'markdown_edit_save_error',
  MultiSessionCreateError: 'multi_session_create_error',
  PlanDowngradeError: 'plan_downgrade_error',
  PlanUpgradeError: 'plan_upgrade_error',
  PlanUpgradeFailed: 'plan_upgrade_failed',
  ProgressNoteCreateError: 'progress_note_create_error',
  ProgressNoteRegenerateError: 'progress_note_regenerate_error',
  SignupFailed: 'signup_failed',
  SpeakerChangeError: 'speaker_change_error',
  SubscriptionCancelError: 'subscription_cancel_error',
  TranscriptSaveError: 'transcript_save_error',
  UserInfoEditFailed: 'user_info_edit_failed',
} as const;

export type MixpanelError = (typeof MixpanelError)[keyof typeof MixpanelError];
